# Using Timelink in notebooks: tutorial

> First time use: follow instructions in the [README.md](README.md) file in this directory.

In [2]:
import timelink
timelink.version

'1.1.10'

## Initial setup

Create a TimelinkNotebook object. This will be the interface for most of your interactions with Timelink.

The first time you run this notebook, you will be prompted to install ìpykernel. This is required to run Timelink in a notebook.

Note:
* First time run takes a little time as the required Docker images are downloaded.
* Timelink will default to using sqlite as the database, see [Receipts notebook for more control](1-receipts.ipynb)

In [1]:
from timelink.notebooks import TimelinkNotebook

tlnb = TimelinkNotebook()

WARNING:root:Reusing existing container sharp_lamarr

TimelinkNotebook created a database to store data and a Kleio server to 
translate transcriptions in Kleio notation into data that can be imported
into a database.

To get information about the database and the Kleio server do ```tnlb.print_info()```

In [4]:
tlnb.print_info()

Project name: dehergne-locations
Project home: /Users/jrc/mhk-home/sources/dehergne-locations
Database type: sqlite
Database name: dehergne_locations
Kleio image: timelinkserver/kleio-server
Kleio server token: PJRKa...
Kleio server URL: http://127.0.0.1:8088
Kleio server home: /Users/jrc/mhk-home/sources/dehergne-locations
Kleio server container: elegant_elbakyan
Kleio version requested: latest
Kleio server version: 12.4.567 (2024-02-07 13:02:03)
SQLite directory: /Users/jrc/mhk-home/sources/dehergne-locations/database/sqlite
Call print_info(show_token=True) to show the Kleio Server token
Call print_info(show_password=True) to show the Postgres password
TimelinkNotebook(project_name=dehergne-locations, project_home=/Users/jrc/mhk-home/sources/dehergne-locations, db_type=sqlite, db_name=dehergne_locations, kleio_image=timelinkserver/kleio-server, kleio_version=latest, postgres_image=postgres, postgres_version=latest)

### Database status

Count the number of rows in each table in the database.

In [2]:
tlnb.table_row_count_df()

               table  count
0               acts     28
1    alembic_version      1
2         aregisters      0
3         attributes  26821
4             blinks     98
5   class_attributes     58
6            classes     10
7           entities  32961
8        geoentities    359
9         kleiofiles     29
10             links    101
11           objects      0
12           persons   2132
13         relations   3535
14         rentities     47
15           sources     29
16            syslog      0
17            syspar      0

### Show the kleio files available

In [3]:
kleio_files = tlnb.get_kleio_files()
kleio_files

,path,name,modified,status,translated,errors,warnings,import_status,import_errors,import_warnings,import_error_rpt,import_warning_rpt,imported,rpt_url,xml_url
0,sources/dehergne-0-abrev.cli,dehergne-0-abrev.cli,2025-04-14 05:11:06.124864+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:11:37.299110,/rest/reports/sources/dehergne-0-abrev.rpt,/rest/exports/sources/dehergne-0-abrev.xml
1,sources/dehergne-a.cli,dehergne-a.cli,2025-09-12 08:48:58.334832+00:00,V,2025-09-12 08:48:00+00:00,0,0,I,0,0,No errors,No warnings,2025-09-12 08:49:07.877169,/rest/reports/sources/dehergne-a.rpt,/rest/exports/sources/dehergne-a.xml
2,sources/dehergne-b.cli,dehergne-b.cli,2025-09-12 07:03:42.927824+00:00,V,2025-09-12 07:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-09-12 07:03:52.002274,/rest/reports/sources/dehergne-b.rpt,/rest/exports/sources/dehergne-b.xml
3,sources/dehergne-c.cli,dehergne-c.cli,2025-06-09 04:54:52.271057+00:00,V,2025-05-29 14:02:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:48.513367,/rest/reports/sources/dehergne-c.rpt,/rest/exports/sources/dehergne-c.xml
4,sources/dehergne-d.cli,dehergne-d.cli,2025-06-09 04:54:52.275558+00:00,V,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:52.745787,/rest/reports/sources/dehergne-d.rpt,/rest/exports/sources/dehergne-d.xml
5,sources/dehergne-e.cli,dehergne-e.cli,2025-06-09 04:54:52.277401+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:42:54.133535,/rest/reports/sources/dehergne-e.rpt,/rest/exports/sources/dehergne-e.xml
6,sources/dehergne-f.cli,dehergne-f.cli,2025-06-09 04:54:52.278048+00:00,V,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:00.181349,/rest/reports/sources/dehergne-f.rpt,/rest/exports/sources/dehergne-f.xml
7,sources/dehergne-g.cli,dehergne-g.cli,2025-06-09 04:54:52.281060+00:00,V,2025-06-04 00:17:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:06.803211,/rest/reports/sources/dehergne-g.rpt,/rest/exports/sources/dehergne-g.xml
8,sources/dehergne-h.cli,dehergne-h.cli,2025-06-09 04:54:52.283525+00:00,V,2025-05-28 07:32:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:09.234806,/rest/reports/sources/dehergne-h.rpt,/rest/exports/sources/dehergne-h.xml
9,sources/dehergne-i.cli,dehergne-i.cli,2025-06-09 04:54:52.284346+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:10.745085,/rest/reports/sources/dehergne-i.rpt,/rest/exports/sources/dehergne-i.xml
10,sources/dehergne-j.cli,dehergne-j.cli,2025-06-09 04:54:52.284889+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:13.074371,/rest/reports/sources/dehergne-j.rpt,/rest/exports/sources/dehergne-j.xml
11,sources/dehergne-k.cli,dehergne-k.cli,2025-06-09 04:54:52.285703+00:00,V,2025-06-03 14:28:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:15.723110,/rest/reports/sources/dehergne-k.rpt,/rest/exports/sources/dehergne-k.xml
12,sources/dehergne-l.cli,dehergne-l.cli,2025-09-12 08:48:59.810934+00:00,V,2025-09-12 08:48:00+00:00,0,0,I,0,0,No errors,No warnings,2025-09-12 08:49:14.556076,/rest/reports/sources/dehergne-l.rpt,/rest/exports/sources/dehergne-l.xml
13,sources/dehergne-locations-1644.cli,dehergne-locations-1644.cli,2025-06-09 04:54:52.289953+00:00,V,2025-06-06 02:43:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:25.590499,/rest/reports/sources/dehergne-locations-1644.rpt,/rest/exports/sources/dehergne-locations-1644.xml
14,sources/dehergne-locations-1701.cli,dehergne-locations-1701.cli,2025-06-09 04:54:52.291489+00:00,V,2025-06-05 03:13:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:28.167601,/rest/reports/sources/dehergne-locations-1701.rpt,/rest/exports/sources/dehergne-locations-1701.xml
15,sources/dehergne-m.cli,dehergne-m.cli,2025-06-09 04:54:52.292952+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:35.975599,/rest/reports/sources/dehergne-m.rpt,/rest/exports/sources/dehergne-m.xml
16,sources/dehergne-n.cli,dehergne-n.cli,2025-04-14 05:11:22.734506+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:12:30.418032,/rest/reports/sources/dehergne-n.rpt,/rest/exports/sources/dehergne-n.xml
17,sources/dehergne-o.cli,dehergne-o.cli,2025-06-09 04:54:52.297238+00:00,V,2025-06-04 00:22:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:37.571776,/rest/reports/sources/dehergne-o.rpt,/rest/exports/sources/dehergne-o.xml
18,sources/dehergne-p.cli,dehergne-p.cli,2025-06-09 04:54:52.297937+00:00,V,2025-06-05 03:03:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:44.220866,/rest/reports/sources/dehergne-p.rpt,/rest/exports/sources/dehergne-p.xml
19,sources/dehergne-q.cli,dehergne-q.cli,2025-04-14 05:11:24.903064+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:12:38.476645,/rest/reports/sources/dehergne-q.rpt,/rest/exports/sources/dehergne-q.xml
20,sources/dehergne-r.cli,dehergne-r.cli,2025-09-12 07:01:57.109509+00:00,V,2025-09-12 07:01:00+00:00,0,0,I,0,0,No errors,No warnings,2025-09-12 07:02:17.568444,/rest/reports/sources/dehergne-r.rpt,/rest/exports/sources/dehergne-r.xml
21,sources/dehergne-s.cli,dehergne-s.cli,2025-06-09 04:54:52.304647+00:00,V,2025-05-28 09:27:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:43:59.107317,/rest/reports/sources/dehergne-s.rpt,/rest/exports/sources/dehergne-s.xml
22,sources/dehergne-t.cli,dehergne-t.cli,2025-06-09 04:54:52.307814+00:00,V,2025-05-28 11:51:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:03.627749,/rest/reports/sources/dehergne-t.rpt,/rest/exports/sources/dehergne-t.xml
23,sources/dehergne-u.cli,dehergne-u.cli,2025-04-14 05:11:31.500511+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:12:54.779184,/rest/reports/sources/dehergne-u.rpt,/rest/exports/sources/dehergne-u.xml
24,sources/dehergne-v.cli,dehergne-v.cli,2025-06-09 04:54:52.309741+00:00,V,2025-05-28 08:05:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:09.658966,/rest/reports/sources/dehergne-v.rpt,/rest/exports/sources/dehergne-v.xml
25,sources/dehergne-w.cli,dehergne-w.cli,2025-06-09 04:54:52.311802+00:00,V,2025-05-28 08:26:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:11.169602,/rest/reports/sources/dehergne-w.rpt,/rest/exports/sources/dehergne-w.xml
26,sources/dehergne-x.cli,dehergne-x.cli,2025-06-09 04:54:52.312263+00:00,V,2025-06-03 14:25:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:12.995343,/rest/reports/sources/dehergne-x.rpt,/rest/exports/sources/dehergne-x.xml
27,sources/dehergne-y.cli,dehergne-y.cli,2025-06-09 04:54:52.312894+00:00,V,2025-05-28 08:31:00+00:00,0,0,I,0,0,No errors,No warnings,2025-06-09 04:44:14.410675,/rest/reports/sources/dehergne-y.rpt,/rest/exports/sources/dehergne-y.xml
28,sources/dehergne-z.cli,dehergne-z.cli,2025-04-14 05:11:35.345099+00:00,V,2025-04-14 05:11:00+00:00,0,0,I,0,0,No errors,No warnings,2025-04-14 05:38:12.989318,/rest/reports/sources/dehergne-z.rpt,/rest/exports/sources/dehergne-z.xml

## Optionally clean translations

In [4]:
# tlnb.kleio_server.translation_clean("", recurse="yes")


# Update the database from Kleio sources.

Updates source translations and imports into database sources with no errors.

Only changed files since last import, or new files, will be processed.

In [5]:
import logging
logging.basicConfig(level=logging.INFO)

tlnb.update_from_sources()

## Check the status of the files

Check the import status of the translated files

I: Imported

E: Imported with error

W: Imported with warnings no errors

N: Not imported

U: Translation updated need to reimport

In [6]:
imported_files_df = tlnb.get_import_status()
imported_files_df[["import_status","import_errors","import_warnings","name","errors","warnings","path"]].sort_values("name")

,import_status,import_errors,import_warnings,name,errors,warnings,path
0,I,0,0,dehergne-0-abrev.cli,0,0,sources/dehergne-0-abrev.cli
1,I,0,0,dehergne-a.cli,0,0,sources/dehergne-a.cli
2,I,0,0,dehergne-b.cli,0,0,sources/dehergne-b.cli
3,I,0,0,dehergne-c.cli,0,0,sources/dehergne-c.cli
4,I,0,0,dehergne-d.cli,0,0,sources/dehergne-d.cli
5,I,0,0,dehergne-e.cli,0,0,sources/dehergne-e.cli
6,I,0,0,dehergne-f.cli,0,0,sources/dehergne-f.cli
7,I,0,0,dehergne-g.cli,0,0,sources/dehergne-g.cli
8,I,0,0,dehergne-h.cli,0,0,sources/dehergne-h.cli
9,I,0,0,dehergne-i.cli,0,0,sources/dehergne-i.cli
10,I,0,0,dehergne-j.cli,0,0,sources/dehergne-j.cli
11,I,0,0,dehergne-k.cli,0,0,sources/dehergne-k.cli
12,I,0,0,dehergne-l.cli,0,0,sources/dehergne-l.cli
13,I,0,0,dehergne-locations-1644.cli,0,0,sources/dehergne-locations-1644.cli
14,I,0,0,dehergne-locations-1701.cli,0,0,sources/dehergne-locations-1701.cli
15,I,0,0,dehergne-m.cli,0,0,sources/dehergne-m.cli
16,I,0,0,dehergne-n.cli,0,0,sources/dehergne-n.cli
17,I,0,0,dehergne-o.cli,0,0,sources/dehergne-o.cli
18,I,0,0,dehergne-p.cli,0,0,sources/dehergne-p.cli
19,I,0,0,dehergne-q.cli,0,0,sources/dehergne-q.cli
20,I,0,0,dehergne-r.cli,0,0,sources/dehergne-r.cli
21,I,0,0,dehergne-s.cli,0,0,sources/dehergne-s.cli
22,I,0,0,dehergne-t.cli,0,0,sources/dehergne-t.cli
23,I,0,0,dehergne-u.cli,0,0,sources/dehergne-u.cli
24,I,0,0,dehergne-v.cli,0,0,sources/dehergne-v.cli
25,I,0,0,dehergne-w.cli,0,0,sources/dehergne-w.cli
26,I,0,0,dehergne-x.cli,0,0,sources/dehergne-x.cli
27,I,0,0,dehergne-y.cli,0,0,sources/dehergne-y.cli
28,I,0,0,dehergne-z.cli,0,0,sources/dehergne-z.cli

### Check the translation report

In [7]:
rpt = tlnb.get_translation_report(imported_files_df, 12)
print(rpt)

KleioTranslator - server version 12.9 - build 588 2025-06-06 16:04:22
12-9-2025 8-48

Processing data file dehergne-l.cli
-------------------------------------------
Generic Act translation module with geoentities (XML).
     Joaquim Ramos de Carvalho (joaquim@uc.pt)
** New document: kleio
=========================
kleio translation started
=========================
Structure: gacto2.str
Prefix:
Autorel:
Translation count: 190
Obs:
** Processing source fonte$dehergne-l
13: lista$dehergne-notices-l
*** End of File

Line 400 "SAME AS" TO EXTERNAL REFERENCE EXPORTED (deh-gabriel-leonard-de-brossard) CHECK IF IT EXISTS BEFORE IMPORTING THIS FILE.
Line 1066 "SAME AS" TO EXTERNAL REFERENCE EXPORTED (deh-pierre-martial-cibot) CHECK IF IT EXISTS BEFORE IMPORTING THIS FILE.
Line 1578 "SAME AS" TO EXTERNAL REFERENCE EXPORTED (deh-manuel-mendes) CHECK IF IT EXISTS BEFORE IMPORTING THIS FILE.

Structure file: /kleio-home/structures/sources.str
Structure processing report: /kleio-home/structures/sources.srpt
Structure in JSON: /kleio-home/structures/sources.str.json

Kleio file: /kleio-home/sources/dehergne-l.cli
Original file: /kleio-home/sources/dehergne-l.org
Previous version: /kleio-home/sources/dehergne-l.old
Temp file with ids: /kleio-home/sources/dehergne-l.ids
** - /kleio-home/sources/dehergne-l.cli-renamed to- /kleio-home/sources/dehergne-l.old
0  errors.
0  warnings.
Groups in this file:[irmao,referida,rel,referido,mae,pai,ls,n,lista,fonte,link,kleio]
Translation finished.

### Get the import report for a file

In case there are errors in the import phase check the import report.

In [8]:
rpt = tlnb.get_import_rpt(imported_files_df, rows=[13])
print(rpt)

dehergne-locations-1644.cli
No errors
No warnings

## Todo

This as data frame in a single function
* TimelinkNotebook.translate([files_df,paths=List[str], rows=List[int],status="T"])
* TimelinkNotebook.import([files_df,paths=List[str], rows=List[int],status="V"])


# Obter dados /  Getting data

### Procurar pessoa, mostrar em notação Kleio

---
### Search for people, show in Kleio notation

In [9]:
from timelink.api.models import Person

show_only=10

with tlnb.db.session() as session:
    ricci = session.query(Person).filter(Person.name.like('%Ricci')).all()

    for mr in ricci[:show_only]:
        print(mr.to_kleio())
        print()

referido$Matteo Ricci/m/id=deh-lazzaro-cattaneo-ref1
  ls$jesuita-tarefa/Toma o hábito de letrado/
  ls$tarefa/Romaniza os cinco tons do chinês/
  <rel$sociabilidade/Companheiro/Lazzaro Cattaneo/deh-lazzaro-cattaneo/1594
  ls$estadia/Shiuchow (Chao-tcheou)#@wikidata:Q1346617/1594
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1346617"%Shiuchow (Chao-tcheou)/1594

referido$Matteo Ricci/m/id=deh-giovanni-cola-niccolo-ref1
  <rel$sociabilidade/Companheiro/Giovanni Cola Niccolò/deh-giovanni-cola-niccolo/1582-08-07
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1582-08-07
  ls$chegada/Macau#@wikidata:Q14773/1582-08-07

referido$Matteo Ricci/m/id=deh-sabatino-de-ursis-ref1
  rel$institucional/Envia a Pequim/Sabatino De Ursis/deh-sabatino-de-ursis-ref1/
  <rel$sociabilidade/Companheiro/Sabatino De Ursis/deh-sabatino-de-ursis/1617-03-18

referido$Matteo Ricci/m/id=deh-jean-fernandes-tchong-ref1
  rel$sociabilidade/Envia em auxílio de Bento de Góis/Jean Fernandes Tchong/deh-jean-fernandes-tchong-ref1/1606

referido$Matteo Ricci/m/id=deh-sebastien-fernandes-tchong-ref2
  ls$tarefa/Estuda chinês e latim#com Tchong/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nanchang (Nantch'ang, Kiangsi)/
  ls$estadia/Nanchang (Nantch'ang, Kiangsi)#@wikidata:Q171943/
  <rel$sociabilidade/Companheiro/Sébastien Fernandes Tchong/deh-sebastien-fernandes-tchong/1591-01-01
  ls$jesuita-cargo/Mestre dos Noviços/1591-01-01
  <rel$sociabilidade/Companheiro/Sébastien Fernandes Tchong/deh-sebastien-fernandes-tchong/1598-09-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1598-09-07
  ls$estadia/Pequim#@wikidata:Q956/1598-09-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1598-11-05
  ls$estadia/Pequim#@wikidata:Q956/1598-11-05

referido$Matteo Ricci/m/id=deh-bento-de-gois-ref2
  rel$sociabilidade/Envia em auxílio de Bento de Góis/Jean Fernandes Tchong/deh-bento-de-gois-ref2/1606/obs=a data vem da entrada de Jean Fernandes Tchong

referido$Matteo Ricci/m/id=deh-manuel-pereira-yeou-ref1
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1610
  ls$morte/Pequim#@wikidata:Q956/1610

n$Matteo Ricci/m/id=deh-matteo-ricci
  <rel$parentesco/pai/Giovanni Battista Ricci/deh-matteo-ricci-pai/
  <rel$parentesco/mae/Giovanna Angiolelli/deh-matteo-ricci-mae/
  <rel$identification/same as/Matteo Ricci/deh-joao-barradas-ref1/
  ls$nacionalidade/Itália/
  ls$jesuita-estatuto/Padre/
  ls$nome-chines/Li Ma-teou/
  ls$nome-chines/Si-T'ai/
  ls$tarefa/Calendário cristão na China#introduz?/
  ls$dehergne/684//obs=Ricci, Matteo (ital.) P. 684 Li Ma-teou, Si-T'al (Pf.., et non Ki-Jen, RBS 218)., en portugais Richo (DI. XI, 155, n. 19). N. 6 oct. 1552, Macerata, dans la Marche d'Ancône. E. noviciat St André du Quirinal, Rome, 16 août 1571 (Rom. 171A, 16: il signe: Matteo Riccio). Emb. sur le S. Luis, 24 mars 1578 (W 200)., arr. Goa, 13 sept., et Macao, 7 août 1582., août 1583, Canton., 10 sept. 1583, Shiuhing (Tchao-k'ing fou), où il fonde une résidence., oct. 1589, résidence à Shiuchow (Chao-tcheou)., du 21 mai 1595 au 15 juin, Nankin., 28 juin 1596 au 25 juin 1598, Nan-tch'ang fou., 5 juill. 1599, Nankin., 19 mai 1600, départ pour Pékin où il arr. le 24 janv. 1601, et où il fonde la mission du Hopei, 1601., Supérieur de la mission de Chine, d'août 1597 à sa mort., 1609, congrégation mariale. Pékin., calendrier chrétien en Chine (Pf. 117).
  ls$dehergne/684//obs=P. 25 juill. 1580, à Cochin, où il célèbre sa première messe le 26 juill. (D'Elia III, 22). V. Nan-tch'ang 1er janv. 1596 (D'Elia I, 374 et II, 4) pr. « Nanciani » ... Riccius (Lus. 2, 128). M. 11 mai 1610, Pékin (JS 113, 120-146., Planchet p. 222). Fils de Giovanni Battista Ricci, pharmacien, et de Giovanna Angiolelli, famille noble, marquis de Castelvecchio (D'Elia I, cii et II, 550). HS 43, 58 le fait mourir d'abord en 1609, puis le 11 mai 1610. Portrait: Pf. 31., D'Elia I, p. vi., ARSI Rom. 185, f° 97-98., BN: Estampes, Ne 100., en couleurs dans Bortone, P. Fernando,- Gesuiti alla corte di Pechino, 1969, pl. II p. 1., cf. Hamy. Pf. 22., Koch., NCE (F. A. Rouleau)., EC (Cel. Testore)., EB (J.S. Sebes)., CE (J. Brucker)., El (Tacchi Venturi). Bibliographie: SiRErr IV, p. 525-528., XII, p. 275-283., XIV. 1. p. 778.,
  ls$dehergne/684//obs=D'Elu III, 239-243. Biographie: en chinois: BN: Courant 9 (anonyme), 1014-1016 I, par Aleni, 1321 (par Pantoja, de Ursis)., et 6832 I, poème sur Rica. BernardE-MaÎtre], H., Le P. Matthieu Ricci et la société chinoise de son temps (1552-1610), Tientsin, 1937, 2 vol.., trad. chinoise par Wang Tch'ang-Tche, J., 1943., du même, Iles Philippines, 213-218 (sur la pensée de Ricci)., Cronin, Vincent, The Wise Man front the West, Londres, 1955., Dunne, G. H., Génération of Giants, 1962, p. 23-108., trad. franç. Chinois avec les Chinois, te P. Ricci et ses compagnons, Paris, 1964., Bortone, Fernando, P. Matteo Ricci, SJ.: Il « Saggio d'Occidente », 2' éd., 1965., trad. franç. en préparation. Le ms de Pires, Francisco, montre qu'il a failli être envoyé au Japon.Son oeuvre: Nocentini, Lod., --primo Sinologo, P.M.R., Florence, 1882.,
  ls$dehergne/684//obs=Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,. Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1., Son oeuvre: Nocentini, Lod., -- primo Sinologo, P.M.R., Florence, 1882., Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,- Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1.,
  ls$dehergne/684//obs=id.. L'apport scientifique du P. M. R à la Chine, Tientsin, 1935, dont trad. anglaise par Chalmers Werner, Edw., Pékin, 1935., id., L'attitude du P. M. R. en face des coutumes et rites chinois, RSRel. 28 (1938), 31-47., id., Les étapes de la cartographie scientifique pour ta Chine et tes pays voisins, MS I (1936), 428-477., Brou, A., Les tâtonnements du P. M. R., RHM 15 (1938), 228-244., Szczesniak, B., The Seventeenth Maps of China, Imago Mundi 17 (1956), 116-136, 9 cartes., id., Matteo Ricci's Maps of China, ibid , 11 (1954), 127-134., cf Giles, L., Geographicat Journal 52 (1918), 367-385 et 53 (1919), 19-30., Wallis, Helen, The Influence of Father R. on Far Eastern Cartography, Imago Mundi 19 (1965), 38-45, 5 cartes., Harris, George L., The Mission of M. R. A case study of an effort at guided culture change in the Sixteenth Century, MS 25 (1968), 1-168.,
  ls$dehergne/684//obs=Bettray, Johannes, S.V.D., Die akkomodationmethode des P. M. R., S.J., in China, Analecta Gregoriana, nº 76, Rome, 411 p.., Rule, Paul A., Jestât and Confucian? Chinese Religion in the journal of M.R, Journal of Religious History (Sidney, 1969), 105-124., D'Elia, P. M., Récent discoveries and New Studies (1938-1960) on the World Map in Chinese of F. M.R., SJ., MS XX (1961), 82-164., Danibl-Rops, Histoire de t'Eglise du Christ VI (Paris, 1966), 272-276, Le Christ entre au « Cathay » avec « Li Mateou »., Schutte, 996., DI. XII, 1031. Et nombre d'études sur des points spéciaux., par exemple, sur la Congré- gation mariale de Pékin: Du Manoir, Hubert, Maria t. IV, 968-972., NZM 1962, 255 citant Margiotti...
  ls$dehergne/684//obs=Sur l'art chinois: Sepp Schûller, P. M. Ricci und die christliche Kunst, Die Kath. Miss. LXIV (Diisseldorf, 1936), 3-8., H. Bernard [Maître], L'Art chré- tien en Chine au temps du P. M. R., RHM 12 (1935), 199-229., D'Elia, Le origini delt'arte cristiana cinese, Rome 1939. Sur l'influence au Japon des cartes de Ricci, Aleni et Verbiest, l'art, de Shintarô Ayusawa, MNipp. 19 (1964), 45-49. Sur le Ki-jen che p'ien, RBS 228 et 399. Principaux autographes de RICCI: — Son catéchisme, B. Casanatense ms 2136 G. I 1, daté de 1603, cf. JS 195.
  ls$dehergne/684//obs=— Délia Entrata delta Comp. nella Cina, avec additions de N. Trigault, JS 106a. Cf D'Elia. Une édition nouvelle, avec un important appareil documentaire et critique est en préparation à l'Université de Paris VII (Bulletin de Liaison, Ecole Pratique des Hautes Etudes, VI* section, 54 bd Raspail, 75006 Paris, vol. V (1972) p. 42. — La Carte de Chine, 28 sept. 1584, reproduite dans Colin, Francisco & Pastells, Pablo, Labor Evangelica .... Barcelone, 1902, III, planche, p. 448 (Arch. d. Ind., 145-7-7). Sa carte du Monde, supra. Gaibandi, Pietro, -- P. M.R e ta geografia délia Cina, Rivista di fisica, matematica e scienze naturali, Padua, VIII, 1903, 321-355, 459-464.
  ls$dehergne/684//obs=pécimen d'écriture, nom chinois et romanisation, Allan, pl. p. 49 (noter le -RI de Ricci, écrit à la fois RI et LI. Copie de la lettre du P. « Matheo Risi y Saliano » (1584) à Juan Bautista RomAn, facteur des îles Philippines à Macao, dans Carlos Sanz, Primitivas Relaciones de Espana con Asia y Oceania, Madrid, 1958, 372-384 (Archivos de Indias 67-6-29) et l'art, de Léon Lopetegui, Miss. Hisp. I, 1944, 341-352., Razén y Fe IV, 1902, 463477.
  ls$nota/JRC//obs="""

            Schutte, Monumenta historica japoniae I. 1280
            “18. Maji 1577 Roma discessit, in Lusitaniam se
            contulit, Conimbricae studio deditus;
            24. Martii 1578 e Lusitania in Indiam solvit,
            13. Sept. 1578 Goam advenit. Cochini deinceps
            et Goae studium prosecu-tus. litt. quoque human. docuit.”

            """
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q13135"%Macerata/1552-10-06
  ls$nascimento/Macerata#@wikidata:Q13135/1552-10-06
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q220"%Roma/1571-08-16
  ls$jesuita-entrada/Roma#@wikidata:Q220%(Noviciado de Sant'Andrea al Quirinale)/1571-08-16
  ls$partida-x/Roma#@wikidata:Q220/1577-05-18/obs=Schutte, Monumenta historica japoniae I.1280
  ls$partida-x@wikidata/"https://www.wikidata.org/wiki/Q220"%Roma/1577-05-18
  ls$estadia-x@wikidata/"https://www.wikidata.org/wiki/Q45412"%Coimbra/1577-06
  ls$estadia-x/Coimbra#@wikidata:Q45412/1577-06/obs="""
                  Ricci and Tacchi Venturi, Opere Storiche Del p. Matteo Ricci s. i.
                     de Junho de 1577 a fim de março de 1578, p. lxiii

                  Schutte, Monumenta historica japoniae I. 1280"""
  ls$embarque/S. Luís/1578-03-24
  ls$wicky/200/1578-03-24
  ls$wicky-viagem/25/1578-03-24
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q1171"%Goa/1578-09-13
  ls$chegada/Goa#@wikidata:Q1171/1578-09-13
  ls$jesuita-ordenacao-padre@wikidata/"https://www.wikidata.org/wiki/Q1800"%Cochim/1580-07-25
  ls$jesuita-ordenacao-padre/Cochim#@wikidata:Q1800/1580-07-25
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1800"%Cochim/1580-07-26
  ls$estadia/Cochim#@wikidata:Q1800/1580-07-26
  ls$tarefa/Celebra a primeira missa/1580-07-26
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1582-08-07
  ls$chegada/Macau#@wikidata:Q14773/1582-08-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16572"%Cantão/1583-08
  ls$estadia/Cantão#@wikidata:Q16572/1583-08
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q59164"%Shiuhing (Tchao-k'ing fou)/1583-09-10
  ls$estadia/Shiuhing (Tchao-k'ing fou)#@wikidata:Q59164/1583-09-10
  ls$jesuita-tarefa/Funda uma residência em Shiuhing/1583-09-10#depois
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1346617"%Shiuchow (Chao-tcheou)/1589-10
  ls$estadia/Shiuchow (Chao-tcheou)#@wikidata:Q1346617/1589-10
  ls$jesuita-tarefa/Funda uma residência em Shiuchow#?/1589-10#depois
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1595-05-21
  ls$estadia/Nanquim#@wikidata:Q16666/1595-05-21
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1595-06-15
  ls$estadia/Nanquim#@wikidata:Q16666/1595-06-15
  ls$jesuita-votos/4V/1596-01-01
  ls$jesuita-votos-local@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang/1596-01-01
  ls$jesuita-votos-local/Nan-tch'ang#@wikidata:Q171943/1596-01-01
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang fou/1596-06-28
  ls$estadia/Nan-tch'ang fou#@wikidata:Q171943/1596-06-28
  ls$jesuita-cargo/Superior da missão da China/1597-08
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang fou/1598-06-25
  ls$estadia/Nan-tch'ang fou#@wikidata:Q171943/1598-06-25
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1599-07-05
  ls$estadia/Nanquim#@wikidata:Q16666/1599-07-05
  ls$partida@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1600-05-19
  ls$partida/Pequim#@wikidata:Q956/1600-05-19
  ls$jesuita-tarefa/Funda a missão do Hopei/1601
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1601-01-24
  ls$chegada/Pequim#@wikidata:Q956/1601-01-24
  ls$estadia/Pequim#@wikidata:Q956/1609
  ls$jesuita-tarefa/Congregação marial de Pequim#funda?/1609
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1609
  ls$jesuita-cargo/Superior da missão da China/1610-05-11
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1610-05-11
  ls$morte/Pequim#@wikidata:Q956/1610-05-11
  pai$Giovanni Battista Ricci/m/id=deh-matteo-ricci-pai
    rel$parentesco/pai/Matteo Ricci/deh-matteo-ricci-pai/
    rel$parentesco/marido/Giovanna Angiolelli/deh-matteo-ricci-pai/
    ls$profissao/Boticário/
    ls$ec/c/1588
  mae$Giovanna Angiolelli/f/id=deh-matteo-ricci-mae/obs="""      Dehergne menciona família nobre, marqueses de Castelvecchio, mas não diz de
  que lado
  """
    <rel$parentesco/marido/Giovanni Battista Ricci/deh-matteo-ricci-pai/
    rel$parentesco/mae/Matteo Ricci/deh-matteo-ricci-mae/
    ls$ec/c/1588

pai$Giovanni Battista Ricci/m/id=deh-matteo-ricci-pai
  rel$parentesco/pai/Matteo Ricci/deh-matteo-ricci-pai/
  rel$parentesco/marido/Giovanna Angiolelli/deh-matteo-ricci-pai/
  ls$profissao/Boticário/
  ls$ec/c/1588

referido$Mateo Ricci/m/id=deh-joao-rodrigues-tcuzu-ref2
  <rel$institucional/Adversário/João Rodrigues Tçuzu/deh-joao-rodrigues-tcuzu/

In [12]:
from sqlalchemy import select

from timelink.api.models import Person, Attribute

show_only=10

with tlnb.db.session() as session:
    stmt = select(Person).join(Person.attributes.and_(Attribute.the_type == 'estadia',
                                                      Attribute.the_value.like('Pequim')))
    print(stmt)
    persons = session.execute(stmt).scalars().all()

    for person in persons[:show_only]:
        tlnb.db.pperson(person.id)

/var/folders/gw/vd1jv7ds1hs_m54nfr94nxj80000gn/T/ipykernel_48810/4222805601.py:10: SAWarning: An alias is being generated automatically against joined entity Mapper[Attribute(attributes)] due to overlapping tables.  This is a legacy pattern which may be deprecated in a later release.  Use the aliased(<entity>, flat=True) construct explicitly, see the linked example. (Background on this warning at: https://sqlalche.me/e/20/xaj2)
  print(stmt)

SELECT persons.id, entities.id AS id_1, entities.class, entities.inside, entities.the_source, entities.the_order, entities.the_level, entities.the_line, entities.groupname, entities.extra_info, entities.updated, entities.indexed, persons.name, persons.sex, persons.obs
FROM entities JOIN persons ON entities.id = persons.id JOIN (entities AS entities_1 JOIN attributes AS attributes_1 ON attributes_1.id = entities_1.id) ON entities.id = attributes_1.entity AND attributes_1.the_type = :the_type_1 AND attributes_1.the_value LIKE :the_value_1
n$Jacques Niva Ni/m/id=deh-jacques-niva-ni
  <rel$parentesco/pai/Nome desconhecido/deh-jacques-niva-ni-pai/
  <rel$parentesco/mae/Nome desconhecido/deh-jacques-niva-ni-mae/
  ls$nacionalidade/Japão/
  ls$jesuita-estatuto/Frade Coadjutor/
  ls$nome/Jacques Niwa/
  ls$nome/Jacques Nuia/
  ls$nome/Jacques Neva/
  ls$nome-chines/Ni Ya-kou/
  ls$nome-chines/Yi-Tch'eng/
  ls$profissao/Pintor/
  ls$dehergne/581//obs=Niva Ni (Niwa), Jacques (jap.) fr.coadj. 581 Nula., Neva (Pf.). NI Ya-kou, Yl-Tch'eng (Pf. p. 1066). N. au Japon de père chinois et de mère japonaise 1579., est venu à Macao, comme peintre pour la mission, 1601., puis il passe à Pékin juill. 1602., 1606, à Macao. E. au noviciat à Nan-tch'ang, 1608., Pékin 1611 et mai 1613., Macao 1618, 1623 et 1635. Peintre « au service de la mission de Chine » (catal. Japon 1623). M. 26 oct. 1638, Macao (AHU ms 1659, f 105v). Pf. 124., RHM XII (1935), 220-224 (H. Bernard [Maître])., Die Katholische Missionen, mai 1936, 122-128., John E. McCall, dans Artibus Asiae XI (1948), p. 51 sq., Cieslik, Hubert, Kirishitan-Kunst, NZM 8 (1952), 96-104., 161-177., Schurhammer, Georg, Orientalia, Rome, 1963, 769-780.
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q17"%Japão/1579
  ls$nascimento/Japão#@wikidata:Q17/1579
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1601
  ls$estadia/Macau#@wikidata:Q14773/1601
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1602-07
  ls$estadia/Pequim#@wikidata:Q956/1602-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1606
  ls$estadia/Macau#@wikidata:Q14773/1606
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang/1608
  ls$jesuita-entrada/Nan-tch'ang#@wikidata:Q171943/1608
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1611
  ls$estadia/Pequim#@wikidata:Q956/1611
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1613-05
  ls$estadia/Pequim#@wikidata:Q956/1613-05
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1618
  ls$estadia/Macau#@wikidata:Q14773/1618
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1623
  ls$estadia/Macau#@wikidata:Q14773/1623
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1635
  ls$estadia/Macau#@wikidata:Q14773/1635
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1638-10-26
  ls$morte/Macau#@wikidata:Q14773/1638-10-26
  pai$Nome desconhecido/m/id=deh-jacques-niva-ni-pai
    rel$parentesco/pai/Jacques Niva Ni/deh-jacques-niva-ni-pai/
    rel$parentesco/marido/Nome desconhecido/deh-jacques-niva-ni-pai/
    ls$nacionalidade/China/
    ls$ec/c/1704-05-13
  mae$Nome desconhecido/f/id=deh-jacques-niva-ni-mae
    <rel$parentesco/marido/Nome desconhecido/deh-jacques-niva-ni-pai/
    rel$parentesco/mae/Jacques Niva Ni/deh-jacques-niva-ni-mae/
    ls$nacionalidade/Japão/
    ls$ec/c/1704-05-13
n$Jacques Niva Ni/m/id=deh-jacques-niva-ni
  <rel$parentesco/pai/Nome desconhecido/deh-jacques-niva-ni-pai/
  <rel$parentesco/mae/Nome desconhecido/deh-jacques-niva-ni-mae/
  ls$nacionalidade/Japão/
  ls$jesuita-estatuto/Frade Coadjutor/
  ls$nome/Jacques Niwa/
  ls$nome/Jacques Nuia/
  ls$nome/Jacques Neva/
  ls$nome-chines/Ni Ya-kou/
  ls$nome-chines/Yi-Tch'eng/
  ls$profissao/Pintor/
  ls$dehergne/581//obs=Niva Ni (Niwa), Jacques (jap.) fr.coadj. 581 Nula., Neva (Pf.). NI Ya-kou, Yl-Tch'eng (Pf. p. 1066). N. au Japon de père chinois et de mère japonaise 1579., est venu à Macao, comme peintre pour la mission, 1601., puis il passe à Pékin juill. 1602., 1606, à Macao. E. au noviciat à Nan-tch'ang, 1608., Pékin 1611 et mai 1613., Macao 1618, 1623 et 1635. Peintre « au service de la mission de Chine » (catal. Japon 1623). M. 26 oct. 1638, Macao (AHU ms 1659, f 105v). Pf. 124., RHM XII (1935), 220-224 (H. Bernard [Maître])., Die Katholische Missionen, mai 1936, 122-128., John E. McCall, dans Artibus Asiae XI (1948), p. 51 sq., Cieslik, Hubert, Kirishitan-Kunst, NZM 8 (1952), 96-104., 161-177., Schurhammer, Georg, Orientalia, Rome, 1963, 769-780.
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q17"%Japão/1579
  ls$nascimento/Japão#@wikidata:Q17/1579
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1601
  ls$estadia/Macau#@wikidata:Q14773/1601
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1602-07
  ls$estadia/Pequim#@wikidata:Q956/1602-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1606
  ls$estadia/Macau#@wikidata:Q14773/1606
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang/1608
  ls$jesuita-entrada/Nan-tch'ang#@wikidata:Q171943/1608
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1611
  ls$estadia/Pequim#@wikidata:Q956/1611
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1613-05
  ls$estadia/Pequim#@wikidata:Q956/1613-05
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1618
  ls$estadia/Macau#@wikidata:Q14773/1618
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1623
  ls$estadia/Macau#@wikidata:Q14773/1623
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1635
  ls$estadia/Macau#@wikidata:Q14773/1635
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1638-10-26
  ls$morte/Macau#@wikidata:Q14773/1638-10-26
  pai$Nome desconhecido/m/id=deh-jacques-niva-ni-pai
    rel$parentesco/pai/Jacques Niva Ni/deh-jacques-niva-ni-pai/
    rel$parentesco/marido/Nome desconhecido/deh-jacques-niva-ni-pai/
    ls$nacionalidade/China/
    ls$ec/c/1704-05-13
  mae$Nome desconhecido/f/id=deh-jacques-niva-ni-mae
    <rel$parentesco/marido/Nome desconhecido/deh-jacques-niva-ni-pai/
    rel$parentesco/mae/Jacques Niva Ni/deh-jacques-niva-ni-mae/
    ls$nacionalidade/Japão/
    ls$ec/c/1704-05-13
n$Jacques Niva Ni/m/id=deh-jacques-niva-ni
  <rel$parentesco/pai/Nome desconhecido/deh-jacques-niva-ni-pai/
  <rel$parentesco/mae/Nome desconhecido/deh-jacques-niva-ni-mae/
  ls$nacionalidade/Japão/
  ls$jesuita-estatuto/Frade Coadjutor/
  ls$nome/Jacques Niwa/
  ls$nome/Jacques Nuia/
  ls$nome/Jacques Neva/
  ls$nome-chines/Ni Ya-kou/
  ls$nome-chines/Yi-Tch'eng/
  ls$profissao/Pintor/
  ls$dehergne/581//obs=Niva Ni (Niwa), Jacques (jap.) fr.coadj. 581 Nula., Neva (Pf.). NI Ya-kou, Yl-Tch'eng (Pf. p. 1066). N. au Japon de père chinois et de mère japonaise 1579., est venu à Macao, comme peintre pour la mission, 1601., puis il passe à Pékin juill. 1602., 1606, à Macao. E. au noviciat à Nan-tch'ang, 1608., Pékin 1611 et mai 1613., Macao 1618, 1623 et 1635. Peintre « au service de la mission de Chine » (catal. Japon 1623). M. 26 oct. 1638, Macao (AHU ms 1659, f 105v). Pf. 124., RHM XII (1935), 220-224 (H. Bernard [Maître])., Die Katholische Missionen, mai 1936, 122-128., John E. McCall, dans Artibus Asiae XI (1948), p. 51 sq., Cieslik, Hubert, Kirishitan-Kunst, NZM 8 (1952), 96-104., 161-177., Schurhammer, Georg, Orientalia, Rome, 1963, 769-780.
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q17"%Japão/1579
  ls$nascimento/Japão#@wikidata:Q17/1579
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1601
  ls$estadia/Macau#@wikidata:Q14773/1601
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1602-07
  ls$estadia/Pequim#@wikidata:Q956/1602-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1606
  ls$estadia/Macau#@wikidata:Q14773/1606
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q171943"%Nan-tch'ang/1608
  ls$jesuita-entrada/Nan-tch'ang#@wikidata:Q171943/1608
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1611
  ls$estadia/Pequim#@wikidata:Q956/1611
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1613-05
  ls$estadia/Pequim#@wikidata:Q956/1613-05
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1618
  ls$estadia/Macau#@wikidata:Q14773/1618
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1623
  ls$estadia/Macau#@wikidata:Q14773/1623
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1635
  ls$estadia/Macau#@wikidata:Q14773/1635
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1638-10-26
  ls$morte/Macau#@wikidata:Q14773/1638-10-26
  pai$Nome desconhecido/m/id=deh-jacques-niva-ni-pai
    rel$parentesco/pai/Jacques Niva Ni/deh-jacques-niva-ni-pai/
    rel$parentesco/marido/Nome desconhecido/deh-jacques-niva-ni-pai/
    ls$nacionalidade/China/
    ls$ec/c/1704-05-13
  mae$Nome desconhecido/f/id=deh-jacques-niva-ni-mae
    <rel$parentesco/marido/Nome desconhecido/deh-jacques-niva-ni-pai/
    rel$parentesco/mae/Jacques Niva Ni/deh-jacques-niva-ni-mae/
    ls$nacionalidade/Japão/
    ls$ec/c/1704-05-13
n$João Francisco Cardoso/m/id=deh-joao-francisco-cardoso
  ls$nacionalidade/Portugal/
  ls$jesuita-estatuto/Padre/
  ls$nome/João Francisco Cardozo/
  ls$nome-chines/Mei Ta-Tch'eng Eul-Tchang/
  ls$tarefa/Leva presentes do rei de Portugal a K'ang Hi/
  ls$tarefa/Elabora mapas das províncias/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q46913"%Shansi-Shensi/
  ls$estadia/Shansi-Shensi#@wikidata:Q46913/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q57052"%Kiangsi/
  ls$estadia/Kiangsi#@wikidata:Q57052/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q15175"%Kwangtung/
  ls$estadia/Kwangtung#@wikidata:Q15175/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q15176"%Kwangsi/
  ls$estadia/Kwangsi#@wikidata:Q15176/
  ls$dehergne/141//obs=Cardoso (Cardozo), Joâo Francisco (port.) (II) P. 141 Mei Ta-Tch'eng Eul-Tchang (Pf.) (écrit: Me Ta Chin, JS 174, 73 et Mey Ta-Tcim, JS 173, 299 et 77, 66). N. 13 juin 1677, Porto de Mós, d. de Léria (JS 179, 256). E. 22 déc. 1692 (Lus. 46, 326). Emb. 1708 pour le Malabar (W 1511): parti de Lisbonne en mars 1710 et A. Macao en octobre, dit Le Blanc (M 409, 411)., porteur de présents du roi de Portugal à K'ang Hi. A. Chine, 1710., juillet 1711, Pékin., va lever les cartes des provinces: Shantung, 1711., puis Shansi-Shensi., Kiangsi., Kwangtung et Kwangsi. V. Pékin 25 févr. 1716, il signe Franciscus (sans Joâo) Cardozo (Lus. 13, 410), pr., entre les mains du P. Kilian « Stumpf provin. Japon.: et vice-prov. Sin.: S. J. Visitor ». M. 14 août 1723, Pékin (JS 179, 256., HS 50, 116v et HS 51, 138., Planchet, p. 170). Pf. 623.
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q1012710"%Porto de Mós, diocese de Leiria/1677-06-13
  ls$nascimento/Porto de Mós, diocese de Leiria#@wikidata:Q1012710/1677-06-13
  ls$jesuita-entrada/?/1692-12-22
  ls$embarque/[Para o Malabar]/1708
  ls$wicky/1511/1708
  ls$wicky-viagem/131/1708
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q597"%Lisboa/1710-03
  ls$estadia/Lisboa#@wikidata:Q597/1710-03
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1710-10
  ls$chegada/Macau#@wikidata:Q14773/1710-10
  ls$estadia/Pequim#@wikidata:Q956/1711
  ls$estadia/Shantung#@wikidata:Q43407/1711
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1711
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q43407"%Shantung/1711
  <rel$institucional/Recebe votos/Kilian Stumpf/deh-joao-francisco-cardoso-ref1/1716-02-25
  ls$jesuita-votos/4V/1716-02-25
  ls$jesuita-votos-local@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1716-02-25
  ls$jesuita-votos-local/Pequim#@wikidata:Q956/1716-02-25
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1723-08-14
  ls$morte/Pequim#@wikidata:Q956/1723-08-14
  referido$Kilian Stumpf/m/id=deh-joao-francisco-cardoso-ref1
    ls$jesuita-estatuto/Padre/
    ls$jesuita-cargo/Provincial do Japão/
    ls$jesuita-cargo/Vice-provincial da China/
    ls$jesuita-cargo/Visitador/
    rel$institucional/Recebe votos/João Francisco Cardoso/deh-joao-francisco-cardoso-ref1/1716-02-25
    ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1716-02-25
    ls$estadia/Pequim#@wikidata:Q956/1716-02-25
referido$Kilian Stumpf/m/id=deh-joao-francisco-cardoso-ref1
  ls$jesuita-estatuto/Padre/
  ls$jesuita-cargo/Provincial do Japão/
  ls$jesuita-cargo/Vice-provincial da China/
  ls$jesuita-cargo/Visitador/
  rel$institucional/Recebe votos/João Francisco Cardoso/deh-joao-francisco-cardoso-ref1/1716-02-25
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1716-02-25
  ls$estadia/Pequim#@wikidata:Q956/1716-02-25
n$Kaspar Castner/m/id=deh-kaspar-castner
  ls$nacionalidade/Alemanha/
  ls$jesuita-estatuto/Padre/
  ls$nome/Kaspar Cazener/
  ls$nome-chines/P'ang Kia-pin Mou-Tchai/
  ls$tarefa/Inventa um novo caminho mais curto para a China, por Timor, sem passar pelo estreito/
  ls$cargo/Tutor do príncipe imperial/
  ls$profissao/Cartógrafo/
  ls$dehergne/157//obs="Castner, Kaspar (allem.) P. 157 Castner., Cazener (Borg. cin. 376, Liste). P'ang Kia-pin (= Gaspard) Mou-Tchai (Pf.). N. 7 févr. 1665, Munich (le 7 oct. selon Koch, DHGE et Streit VII, 2008) -E. 18 sept. 1681, Landsberg (G.Sup. 28, 45). Emb. (mars) 1696 (W 1630)., mai 1697, Macao., désigné pour le Tonkin., 1700, Fatshan., 1701, Sin-houei et île de Sancian (JS 25, 250v)., envoyé à Rome comme procureur, Canton, 14 janv. 1702., retour, emb. 1706 (W 1487a) A. 22 juill. 1707., invente une nouvelle route plus courte par mer, par Timor sans passer par le détroit., Pékin, 22 nov. 1707 (SF VI, 639) où nommé Président du Tribunal des Mathématiques et tuteur du prince impérial., cartographe. V. « in E. Foxanensi prov. Canton », dans l'église de Fatshan, 15 août 1700 (Lus. 12, 100) pr.., il signe: Casparus Castner. M. 9 nov. 1709, Pékin, à 44 ans (HS 50, 85v et 51, 126., JS 173, 258., Planchet p. 172)., le 10 nov., dit JS 173, 169. Pf. 486., DHGE (A. De Bil)., NCE (J. H. Campana)., Streit VII, 2008."
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q1726"%Munique/1665-02-07
  ls$nascimento/Munique#@wikidata:Q1726/1665-02-07#ou 16651007
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q494299"%Landsberg/1681-09-18
  ls$jesuita-entrada/Landsberg#@wikidata:Q494299/1681-09-18
  ls$wicky-viagem/119/1696#16960300 segundo Dehergne
  ls$embarque/?/1696-03
  ls$wicky/1360%1630, corrigido segundo Wicky/1696-03
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1697-05
  ls$estadia/Macau#@wikidata:Q14773/1697-05
  ls$estadia/Fatshan#@wikidata:Q34412/1700
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q34412"%Fatshan/1700
  ls$jesuita-votos/4V/1700-08-15
  ls$jesuita-votos-local@wikidata/"https://www.wikidata.org/wiki/Q34412"%Fatshan (igreja)/1700-08-15
  ls$jesuita-votos-local/Fatshan (igreja)#@wikidata:Q34412/1700-08-15
  ls$estadia/Sin-houi#@wikidata:Q1023903/1701
  ls$estadia/Shangchuan#@wikidata:Q1397551/1701
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1023903"%Sin-houi/1701
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1397551"%Shangchuan/1701
  ls$jesuita-cargo/Procurador da Vice-província da China/1702-01-14
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16572"%Cantão/1702-01-14
  ls$estadia/Cantão#@wikidata:Q16572/1702-01-14
  ls$partida@wikidata/"https://www.wikidata.org/wiki/Q220"%Roma/1702-01-14
  ls$partida/Roma#@wikidata:Q220/1702-01-14
  ls$embarque/?/1706
  ls$wicky/1487a/1706
  ls$wicky-viagem/129/1706
  ls$cargo/Presidente do Tribunal da Matemática de Pequim/1707#? segundo Dehergne p. 307
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q148"%China/1707-07-22
  ls$chegada/China#? @wikidata:Q148/1707-07-22
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1707-11-22
  ls$estadia/Pequim#@wikidata:Q956/1707-11-22
  ls$idade/44/1709-11-09
  ls$morte@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1709-11-09
  ls$morte/Pequim#@wikidata:Q956/1709-11-09#ou 17091110
n$Lazzaro Cattaneo/m/id=deh-lazzaro-cattaneo
  ls$nacionalidade/Itália/
  ls$jesuita-estatuto/Padre/
  ls$nome/Lazzaro Cataneo/
  ls$nome-chines/Kouo Kiu-Tsing Yang-Houang/
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q41562"%Costa da Pescaria/
  ls$estadia/Costa da Pescaria#costa este do Sul da Índia, a norte do Cabo Comorimo @wikidata:Q41562 [Thoothukudi ]/
  ls$jesuita-tarefa/Toma o hábito de letrado/
  ls$tarefa/Romaniza os cinco tons do chinês/
  ls$dehergne/158//obs=Cattaneo (Cataneo), Lazzaro (ital.) P. 158 Kouo Klu-Tslng Yang-Houang (Pf.., Yang-fong, selon Courant, 6880). N. 1560 (1568, selon Streit), Sarzana, en Toscane (JS 134, 303: 66 ans en 1626) -E. 27 févr. 1581, Rome, noviciat St André (Rom. 169. 16). Emb. sur le S. Tomé 1 avr. 1588 (W 302)., arr. 1589, Goa., Côte de la Pêcherie., 1593, Macao., Shiuchow (Chao-tcheou) avec Ricci, ils prennent l'habit de lettrés et « romanisent » les 5 tons du chinois, 1594., 7 sept, au 5 nov. 1598, à Pékin., août 1599, Macao., mars Cattaneo (Cataneo), Lazzaro (ital.) P. 158 Kouo Klu-Tslng Yang-Houang (Pf.., Yang-fong, selon Courant, 6880). N. 1560 (1568, selon Streit), Sarzana, en Toscane (JS 134, 303: 66 ans en 1626) -E. 27 févr. 1581, Rome, noviciat St André (Rom. 169. 16). Emb. sur le S. Tomé 1 avr. 1588 (W 302)., arr. 1589, Goa., Côte de la Pêcherie., 1593, Macao., Shiuchow (Chao-tcheou)#@wikidata:Q1346617 avec Ricci, ils prennent l'habit de lettrés et « romanisent » les 5 tons du chinois, 1594., 7 sept, au 5 nov. 1598, à Pékin
  ls$dehergne/158//obs=août 1599, Macao., mars 1600, Nankin., passages à Macao 1601 et 1602., 1604, Malacca et Macao, procure., sept. 1608 à 1610, premier apôtre de Shanghai et de Kiating, invité par Paul Siu., 8 mai 1611, autre résidence fondée à Hangchow, Tchôkiang., 1620, Kiating., 1622, Hangchow., 1631, Hangchow (D'Elia I, 331-334). P. 1587. V. Canton, 26 mai 1596, pr. (Lus. 2, 139). M. 19 janv. 1640, Hangchow. Pf. 51., DHGE (A. De Bil)., EC (E. Lamalle). Art. de Strizoli dans Marco Polo II et III, Shanghai, 1940-1941., de J. de La Servière, New China Review, (Shanghai 1921) 350-355 et D'Elu, dans Florilegio Apostolico II, Venise 1922, 25-39.
  ls$nascimento/Sarzana#@wikidata:Q160628/1560
  ls$nascimento@wikidata/"https://www.wikidata.org/wiki/Q160628"%Sarzana/1560
  ls$jesuita-entrada@wikidata/"https://www.wikidata.org/wiki/Q220"%Roma/1581-02-27
  ls$jesuita-entrada/Roma#@wikidata:Q220%(Noviciado de Sant'Andrea al Quirinale)/1581-02-27
  ls$jesuita-ordenacao-padre/?/1587
  ls$embarque/S. Tomé/1588-04-01
  ls$wicky/302/1588-04-01
  ls$wicky-viagem/32/1588-04-01
  ls$chegada/Goa#@wikidata:Q1171/1589
  ls$chegada@wikidata/"https://www.wikidata.org/wiki/Q1171"%Goa/1589
  ls$estadia/Macau#@wikidata:Q14773/1593
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1593
  rel$sociabilidade/Companheiro/Matteo Ricci/deh-lazzaro-cattaneo/1594
  ls$estadia/Shiuchow (Chao-tcheou)#@wikidata:Q1346617/1594
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q1346617"%Shiuchow (Chao-tcheou)/1594
  ls$jesuita-votos/4V/1596-05-26
  ls$jesuita-votos-local@wikidata/"https://www.wikidata.org/wiki/Q16572"%Cantão/1596-05-26
  ls$jesuita-votos-local/Cantão#@wikidata:Q16572/1596-05-26
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1598-09-07
  ls$estadia/Pequim#@wikidata:Q956/1598-09-07
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q956"%Pequim/1598-11-05
  ls$estadia/Pequim#@wikidata:Q956/1598-11-05
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q14773"%Macau/1599-08
  ls$estadia/Macau#@wikidata:Q14773/1599-08
  ls$estadia@wikidata/"https://www.wikidata.org/wiki/Q16666"%Nanquim/1600-03
  ls$estadia/Nanquim#@wikidata:Q16666/1600-03



###  Obter um dataframe a partir de atributos

---


###  Get a Dataframe from attributes

#### Exemplo: Missionários que estiveram em Pequim, onde entraram
na ordem, e que nacionalidade tinham.

In [13]:
from timelink.pandas import entities_with_attribute


# Get list of people with with a certain value in a specific attribute
df = entities_with_attribute(
                    entity_type='person',
                    the_type='estadia',
                    the_value='Pequim',
                    more_info=['name'],
                    more_cols=['jesuita-entrada','nacionalidade'],
                    db=tlnb.db,
                    sql_echo=False)
df.info()

TypeError: entities_with_attribute() got an unexpected keyword argument 'more_info'

In [25]:
df.head(55).sort_values('jesuita-entrada')

,name,estadia,estadia.date,estadia.obs,jesuita-entrada,jesuita-entrada.date,jesuita-entrada.obs,nacionalidade,nacionalidade.date,nacionalidade.obs
id,,,,,,,,,,
deh-adrien-grelon,Adrien Grelon,Pequim,16650613,None,?,16430601,None,França,0,None
deh-bernhard-diestel,Bernhard Diestel,Pequim,0,None,?,16391022,None,Alemanha,0,None
deh-bernard-rodes,Bernard Rodes,Pequim,0,None,?,16740707,None,França,0,None
deh-antonio-simoes-i,António Simões,Pequim,17480000,None,?,16780000,None,Portugal,0,None
deh-antonio-leitao,António Leitão,Pequim,16030000,None,?,16030000,None,China,0,None
deh-antonio-de-barros,António de Barros,Pequim,17010700,None,?,16810612,None,Portugal,0,None
deh-antonio-de-barros,António de Barros,Pequim,16971000,None,?,16810612,None,Portugal,0,None
deh-anton-gogeisl,Anton Gogeisl,Pequim,17390301,None,?,17200913,None,Alemanha,0,None
deh-caetano-lopes,Caetano Lopes,Pequim,17270000,None,?,17070217,None,Portugal,0,None
deh-felix-da-rocha,Félix da Rocha,Pequim,17560321,None,?,17280501,None,Portugal,0,None
deh-antoine-de-beauvollier,Antoine de Beauvollier,Pequim,17061017,None,?,16720907,None,França,0,None
deh-alexandre-de-la-charme,Alexandre de La Charme,Pequim,17290300,None,?,17120907,None,França,0,None
deh-andre-palmeiro,André Palmeiro,Pequim,16280000,None,?,15840114,None,Portugal,0,None
deh-adrien-grelon,Adrien Grelon,Pequim,16940900,None,?,16430601,None,França,0,None
deh-andre-pereira,André Pereira,Pequim,17240905,None,?,17070617,None,Portugal,0,None
deh-dominique-parrenin,Dominique Parrenin,Pequim,0,None,Avignon,16850901,None,França,0,None
deh-claude-motel,Claude Motel,Pequim,16650700,None,Avignon,16381111,None,França,0,None
deh-charles-de-belleville,Charles de Belleville,Pequim,16990000,None,Bordeaux,16801125,None,França,0,None
deh-claudio-filippo-grimaldi,Claudio Filippo Grimaldi,Pequim,16940828,None,Chieri,16580113,None,Itália,0,None
deh-claudio-filippo-grimaldi,Claudio Filippo Grimaldi,Pequim,16851107,None,Chieri,16580113,None,Itália,0,None
deh-claudio-filippo-grimaldi,Claudio Filippo Grimaldi,Pequim,16710000,None,Chieri,16580113,None,Itália,0,None
deh-feliciano-da-silva,Feliciano da Silva,Pequim,16110503,None,Coimbra,15931215,None,Portugal,0,None
deh-antonio-de-magalhaes,António de Magalhães,Pequim,17160000,None,Coimbra,16921019,None,Portugal,0,None
deh-antonio-gomes,António Gomes,Pequim,17440000,None,Coimbra,17250528,None,Portugal,0,None
deh-antonio-de-magalhaes,António de Magalhães,Pequim,17261119,com o embaixador português Metello e audiência...,Coimbra,16921019,None,Portugal,0,None
deh-cristoforo-fiori,Cristoforo Fiori,Pequim,16941000,None,Goa,16910000,None,Itália,0,None
deh-antonio-faglia,Antonio Faglia,Pequim,0,None,Génova,16830127,None,Itália,0,None
deh-ehrenbert-xaver-fridelli,Ehrenbert Xaver Fridelli,Pequim,17100000,None,Leoben,16881012,None,Áustria,0,None
deh-ehrenbert-xaver-fridelli,Ehrenbert Xaver Fridelli,Pequim,17210724,None,Leoben,16881012,None,Áustria,0,None
deh-ehrenbert-xaver-fridelli,Ehrenbert Xaver Fridelli,Pequim,17070000,None,Leoben,16881012,None,Áustria,0,None
deh-carlos-de-resende,Carlos de Resende,Pequim,17250000,None,Lisboa,16800218,None,Portugal,0,None
deh-cristoforo-fiori,Cristoforo Fiori,Pequim,16941000,None,Lisboa,16921106,None,Itália,0,None
deh-carlos-de-resende,Carlos de Resende,Pequim,0,None,Lisboa,16800218,None,Portugal,0,None
deh-andrea-giovanni-lubelli,Andrea-Giovanni Lubelli,Pequim,16650000,None,Nápoles,16280330,None,Itália,0,None
deh-etienne-yang,Etienne Yang,Pequim,17890000,None,Paris,17590310,None,China,0,None
deh-etienne-rousset,Etienne Rousset,Pequim,17191100,None,Paris,17140425,None,França,0,None
deh-claude-de-visdelou,Claude de Visdelou,Pequim,16880207,None,Paris,16730905,None,França,0,None
deh-cyr-contancin,Cyr Contancin,Pequim,17110000,None,Paris,16880909,None,França,0,None
deh-aloys-kao,Aloys Kao,Pequim,17510107,None,Paris,17590310,None,China,0,None
deh-aloys-kao,Aloys Kao,Pequim,17660509,None,Paris,17590310,None,China,0,None
deh-emmanuel-de-silva-tchang,Emmanuel de Silva Tchang,Pequim,17430000,None,Pequim,17331031,None,China,0,None
deh-emmanuel-de-silva-tchang,Emmanuel de Silva Tchang,Pequim,17440000,None,Pequim,17331031,None,China,0,None
deh-emmanuel-de-silva-tchang,Emmanuel de Silva Tchang,Pequim,17660000,None,Pequim,17331031,None,China,0,None
deh-domingos-mendes-kieou,Domingos Mendes K'ieou,Pequim,16130000,None,Shiuchow,16050000,None,China,0,None
deh-antoine-gaubil,Antoine Gaubil,Pequim,17400000,None,Toulouse,17040912,None,França,0,None
deh-antoine-thomas,Antoine Thomas,Pequim,16861107,None,Tournai,16600924,None,Bélgica,0,None
deh-christian-wolfgang-henriques-herdtrich,Christian Wolfgang Henriques Herdtrich,Pequim,16730600,None,"Viena, Áustria",16411027,None,Áustria,0,None
deh-august-von-hallerstein,August von Hallerstein,Pequim,17390301,None,"Viena, Áustria",17211027,None,Áustria,0,"território austríaco, actualmente é Eslovénia"
deh-antoine-thomas-ref4,Charles Thomas Maillard de Tournon,Pequim,17052104,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-antonio-de-magalhaes-ref1,Alexandre Metelo de Sousa e Meneses,Pequim,17261119,None,NaN,NaN,NaN,Portugal,0,None
deh-antonio-de-magalhaes-ref2,Yong-Tcheng,Pequim,17261124,None,NaN,NaN,NaN,China,0,None
deh-antonio-francesco-giuseppe-provana-ref1,Charles Thomas Maillard de Tournon,Pequim,17050800,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-caetano-lopes-ref1,Alexandre Metelo de Sousa e Meneses,Pequim,17270000,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-claudio-filippo-grimaldi-ref3,Charles Thomas Maillard de Tournon,Pequim,17060520,None,NaN,NaN,NaN,NaN,NaN,NaN
deh-etienne-rousset-ref1,François Xavier Dentrecolles,Pequim,1721215,None,NaN,NaN,NaN,NaN,NaN,NaN



###  Remover colunas sem valores

---



###  Remove empty columns

In [27]:
df.dropna(how='all', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 247 entries, deh-adrien-grelon to deh-vicent-caun
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  247 non-null    object
 1   estadia               247 non-null    object
 2   estadia.date          247 non-null    object
 3   estadia.obs           15 non-null     object
 4   jesuita-entrada       206 non-null    object
 5   jesuita-entrada.date  206 non-null    object
 6   jesuita-entrada.obs   3 non-null      object
 7   nacionalidade         222 non-null    object
 8   nacionalidade.date    222 non-null    object
 9   nacionalidade.obs     1 non-null      object
dtypes: object(10)
memory usage: 21.2+ KB

In [28]:
df.head(5)

,name,estadia,estadia.date,estadia.obs,jesuita-entrada,jesuita-entrada.date,jesuita-entrada.obs,nacionalidade,nacionalidade.date,nacionalidade.obs
id,,,,,,,,,,
deh-adrien-grelon,Adrien Grelon,Pequim,16650613,None,?,16430601,None,França,0,None
deh-adrien-grelon,Adrien Grelon,Pequim,16940900,None,?,16430601,None,França,0,None
deh-alexandre-de-la-charme,Alexandre de La Charme,Pequim,17290300,None,?,17120907,None,França,0,None
deh-aloys-kao,Aloys Kao,Pequim,17510107,None,Paris,17590310,None,China,0,None
deh-aloys-kao,Aloys Kao,Pequim,17660509,None,Paris,17590310,None,China,0,None


## Contagens

---

## Counting


###  Contagem de atributos a partir de uma tabela em memória

---

###  Count attributes from an existing dataframe

In [29]:
# create a column with the index values which are the id numbers
df['id'] = df.index.values

col = 'jesuita-entrada' # subotal by this column

# Use pandas groupby and specify unique value count for id
df_totals = df.groupby(col).agg({'id':'nunique',
                                                  'estadia':'min',
                                                  'estadia':'max'})

df_totals.sort_values('id',ascending= False).head(30)

                                              id estadia
jesuita-entrada
?                                             58  Pequim
Paris                                         16  Pequim
Lisboa                                         7  Pequim
Nancy                                          7  Pequim
Coimbra                                        6  Pequim
Avignon                                        6  Pequim
Roma                                           5  Pequim
Viena, Áustria                                 4  Pequim
Génova                                         4  Pequim
Nápoles                                        4  Pequim
Roma (Noviciado de Sant'Andrea al Quirinale)   3  Pequim
Landsberg                                      3  Pequim
Bordeaux                                       3  Pequim
Brno, República Checa                          2  Pequim
Macau                                          2  Pequim
Japão                                          2  Pequim
Pequim                                         2  Pequim
Goa                                            2  Pequim
Chieri                                         1  Pequim
Cracóvia                                       1  Pequim
Leoben                                         1  Pequim
Douai                                          1  Pequim
Novellara                                      1  Pequim
Nanquim                                        1  Pequim
Nan-tch'ang                                    1  Pequim
Messina, Sicília                               1  Pequim
Mainz                                          1  Pequim
Mechelen                                       1  Pequim
Portugal                                       1  Pequim
Palermo, Sicília                               1  Pequim


### Contagens na base de dados

Quando o atributo tem muitos valores e não é necessário
ter todas as pessoas em memória: contagem feita na base de dados

---

### Counting directly in the database
When there are many values and it is not
necessary to have all the people in memory:
count directly in the database.

In [44]:
from timelink.pandas import attribute_values

df_totals = attribute_values('estadia', dates_between=("1580-00-00","1610-00-00"),db=tlnb.db)
df_totals.head(20)

                                        count  date_min  date_max
value
Macau                                      38  15800000  16080000
Goa                                        15  15820426  16010501
Japão                                      15  15820220  16090000
Nanquim                                    14  15950521  16090000
Cantão                                     11  15800400  16060200
Nagasaki                                    8  15830725  16060000
Pequim                                      7  15980907  16090000
Roma                                        6  15820000  16080000
Shiuchow (Chao-tcheou)                      6  15891000  16080000
Chao-tcheou                                 4  15910700  16050100
Arima (seminário), Japão                    3  15830000  15880000
China                                       3  15820000  15930000
Malaca                                      3  15820600  16040000
Nan-tch'ang fou                             3  15960628  16090515
Sciaochino (Shiuhing, Tchao-k'ing fou)      3  15820000  15820000
Cantão (feira)                              2  15810400  15810400
Chao-hing                                   2  15850000  15850000
Cochim                                      2  15800726  15970429
Lisboa                                      2  15860411  15960410
México                                      2  15820000  15920000

#### Filtrar por datas

---

#### Filter by dates

In [45]:
df_totals = attribute_values('jesuita-entrada',dates_between=('1580','1600'),db=tlnb.db)

In [47]:
df_totals.head(10)

                           count  date_min  date_max
value
?                             25  15830000  15980000
Coimbra                        7  15840000  15961216
Roma                           5  15800317  15941106
Douai                          2  15941109  15990512
Nápoles                        2  15910908  15971106
Shiuchow, Chao-tcheou fou      2  15891100  15891100
Arona                          1  15960921  15960921
Goa                            1  15870000  15870000
Japão                          1  15801200  15801200
Messina, Sicília               1  15820000  15820000

## Visualizar registos

---

## View records

### Visualizar uma pessoa

---

### View a person

#### Atributos de uma pessoa numa tabela, uma linha por attributo

---

#### Person attributes in a dataframe, one line per attribute

In [48]:
import pandas as pd
from timelink.pandas import group_attributes as person_attributes

pd.set_option('display.max_rows',1000)

id = 'deh-matteo-ricci'
pdf = person_attributes([id],db=tlnb.db)  # note id in a list
pdf[['date','type','value','attr_obs']].sort_values(['date','type'])

,date,type,value,attr_obs
id,,,,
deh-matteo-ricci,0,dehergne,684,"Ricci, Matteo (ital.) P. 684 Li Ma-teou, Si-T'..."
deh-matteo-ricci,0,dehergne,684,"P. 25 juill. 1580, à Cochin, où il célèbre sa ..."
deh-matteo-ricci,0,dehergne,684,"D'Elu III, 239-243. Biographie: en chinois: BN..."
deh-matteo-ricci,0,dehergne,684,"Tacchi-Venturi, Opère storiche del P. M. R., M..."
deh-matteo-ricci,0,dehergne,684,id.. L'apport scientifique du P. M. R à la Chi...
deh-matteo-ricci,0,dehergne,684,"Bettray, Johannes, S.V.D., Die akkomodationmet..."
deh-matteo-ricci,0,dehergne,684,"Sur l'art chinois: Sepp Schûller, P. M. Ricci ..."
deh-matteo-ricci,0,dehergne,684,"— Délia Entrata delta Comp. nella Cina, avec a..."
deh-matteo-ricci,0,dehergne,684,"pécimen d'écriture, nom chinois et romanisatio..."
deh-matteo-ricci,0,jesuita-estatuto,Padre,None
deh-matteo-ricci,0,nacionalidade,Itália,None
deh-matteo-ricci,0,nome-chines,Li Ma-teou,None
deh-matteo-ricci,0,nome-chines,Si-T'ai,None
deh-matteo-ricci,0,tarefa,Calendário cristão na China,None
deh-matteo-ricci,15521006,nascimento,Macerata,None
deh-matteo-ricci,15521006,nascimento@,https://www.wikidata.org/wiki/Q13135,None
deh-matteo-ricci,15710816,jesuita-entrada,Roma (Noviciado de Sant'Andrea al Quirinale),None
deh-matteo-ricci,15710816,jesuita-entrada@,https://www.wikidata.org/wiki/Q220,None
deh-matteo-ricci,15780324,embarque,S. Luís,None
deh-matteo-ricci,15780324,wicky,200,None
deh-matteo-ricci,15780324,wicky-viagem,25,None
deh-matteo-ricci,15780913,chegada,Goa,None
deh-matteo-ricci,15780913,chegada@,https://www.wikidata.org/wiki/Q1171,None
deh-matteo-ricci,15800725,jesuita-ordenacao-padre,Cochim,None
deh-matteo-ricci,15800725,jesuita-ordenacao-padre@,https://www.wikidata.org/wiki/Q1800,None
deh-matteo-ricci,15800726,estadia,Cochim,None
deh-matteo-ricci,15800726,estadia@,https://www.wikidata.org/wiki/Q1800,None
deh-matteo-ricci,15800726,tarefa,Celebra a primeira missa,None
deh-matteo-ricci,15820807,chegada,Macau,None
deh-matteo-ricci,15820807,chegada@,https://www.wikidata.org/wiki/Q14773,None
deh-matteo-ricci,15830800,estadia,Cantão,None
deh-matteo-ricci,15830800,estadia@,https://www.wikidata.org/wiki/Q16572,None
deh-matteo-ricci,15830910,estadia,Shiuhing (Tchao-k'ing fou),None
deh-matteo-ricci,15830910,jesuita-tarefa,Funda uma residência em Shiuhing,None
deh-matteo-ricci,15891000,estadia,Shiuchow (Chao-tcheou),None
deh-matteo-ricci,15891000,jesuita-tarefa,Funda uma residência em Shiuchow,None
deh-matteo-ricci,15950521,estadia,Nanquim,None
deh-matteo-ricci,15950521,estadia@,https://www.wikidata.org/wiki/Q16666,None
deh-matteo-ricci,15950615,estadia,Nanquim,None
deh-matteo-ricci,15950615,estadia@,https://www.wikidata.org/wiki/Q16666,None
deh-matteo-ricci,15960101,jesuita-votos,4V,None
deh-matteo-ricci,15960101,jesuita-votos-local,Nan-tch'ang,None
deh-matteo-ricci,15960628,estadia,Nan-tch'ang fou,None
deh-matteo-ricci,15970800,jesuita-cargo,Superior da missão da China,None
deh-matteo-ricci,15980625,estadia,Nan-tch'ang fou,None
deh-matteo-ricci,15990705,estadia,Nanquim,None
deh-matteo-ricci,15990705,estadia@,https://www.wikidata.org/wiki/Q16666,None
deh-matteo-ricci,16000519,partida,Pequim,None
deh-matteo-ricci,16000519,partida@,https://www.wikidata.org/wiki/Q956,None
deh-matteo-ricci,16010000,jesuita-tarefa,Funda a missão do Hopei,None
deh-matteo-ricci,16010124,chegada,Pequim,None
deh-matteo-ricci,16010124,chegada@,https://www.wikidata.org/wiki/Q956,None
deh-matteo-ricci,16090000,estadia,Pequim,None
deh-matteo-ricci,16090000,estadia@,https://www.wikidata.org/wiki/Q956,None
deh-matteo-ricci,16090000,jesuita-tarefa,Congregação marial de Pequim,None
deh-matteo-ricci,16100511,jesuita-cargo,Superior da missão da China,None
deh-matteo-ricci,16100511,morte,Pequim,None
deh-matteo-ricci,16100511,morte@,https://www.wikidata.org/wiki/Q956,None

In [66]:
p = tlnb.db.get_person(id)
print(p.to_kleio())

n$Matteo Ricci/m/id=deh-matteo-ricci
  rel$function-in-act/n/dehergne-notices-r/0
  ls$nacionalidade/Itália/0
  ls$jesuita-estatuto/Padre/0
  ls$nome-chines/Li Ma-teou/0
  ls$nome-chines/Si-T'ai/0
  ls$nascimento@/"https://www.wikidata.org/wiki/Q13135"/15521006
  ls$nascimento/Macerata/15521006
  ls$jesuita-entrada@/"https://www.wikidata.org/wiki/Q220"/15710816
  ls$jesuita-entrada/Roma (Noviciado de Sant'Andrea al Quirinale)/15710816
  ls$embarque/S. Luís/15780324
  ls$wicky/200/15780324
  ls$wicky-viagem/25/15780324
  ls$chegada@/"https://www.wikidata.org/wiki/Q1171"/15780913
  ls$chegada/Goa/15780913
  ls$estadia@/"https://www.wikidata.org/wiki/Q1800"/15800726
  ls$estadia/Cochim/15800726
  ls$tarefa/Celebra a primeira missa/15800726
  ls$chegada@/"https://www.wikidata.org/wiki/Q14773"/15820807
  ls$chegada/Macau/15820807
  ls$estadia@/"https://www.wikidata.org/wiki/Q16572"/15830800
  ls$estadia/Cantão/15830800
  ls$estadia/Shiuhing (Tchao-k'ing fou)/15830910
  ls$jesuita-tarefa/Funda uma residência em Shiuhing/15830910
  ls$estadia/Shiuchow (Chao-tcheou)/15891000
  ls$jesuita-tarefa/Funda uma residência em Shiuchow/15891000
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/15950521
  ls$estadia/Nanquim/15950521
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/15950615
  ls$estadia/Nanquim/15950615
  ls$estadia/Nan-tch'ang fou/15960628
  ls$jesuita-cargo/Superior da missão da China/15970800
  ls$estadia/Nan-tch'ang fou/15980625
  ls$estadia@/"https://www.wikidata.org/wiki/Q16666"/15990705
  ls$estadia/Nanquim/15990705
  ls$partida@/"https://www.wikidata.org/wiki/Q956"/16000519
  ls$partida/Pequim/16000519
  ls$chegada@/"https://www.wikidata.org/wiki/Q956"/16010124
  ls$chegada/Pequim/16010124
  ls$jesuita-tarefa/Funda a missão do Hopei/16010000
  ls$estadia@/"https://www.wikidata.org/wiki/Q956"/16090000
  ls$estadia/Pequim/16090000
  ls$jesuita-tarefa/Congregação marial de Pequim/16090000
  ls$tarefa/Calendário cristão na China/0
  ls$jesuita-cargo/Superior da missão da China/16100511
  ls$jesuita-ordenacao-padre@/"https://www.wikidata.org/wiki/Q1800"/15800725
  ls$jesuita-ordenacao-padre/Cochim/15800725
  ls$jesuita-votos/4V/15960101
  ls$jesuita-votos-local/Nan-tch'ang/15960101
  ls$morte@/"https://www.wikidata.org/wiki/Q956"/16100511
  ls$morte/Pequim/16100511
  ls$dehergne/684/0/obs="""
      Ricci, Matteo (ital.) P. 684 Li Ma-teou, Si-T'al (Pf.., et non Ki-Jen, RBS 218)., en portugais Richo (DI. XI, 155, n. 19). N. 6 oct. 1552, Macerata, dans la Marche d'Ancône. E. noviciat St André du Quirinal, Rome, 16 août 1571 (Rom. 171A, 16: il signe: Matteo Riccio). Emb. sur le S. Luis, 24 mars 1578 (W 200)., arr. Goa, 13 sept., et Macao, 7 août 1582., août 1583, Canton., 10 sept. 1583, Shiuhing (Tchao-k'ing fou), où il fonde une résidence., oct. 1589, résidence à Shiuchow (Chao-tcheou)., du 21 mai 1595 au 15 juin, Nankin., 28 juin 1596 au 25 juin 1598, Nan-tch'ang fou., 5 juill. 1599, Nankin., 19 mai 1600, départ pour Pékin où il arr. le 24 janv. 1601, et où il fonde la mission du Hopei, 1601., Supérieur de la mission de Chine, d'août 1597 à sa mort., 1609, congrégation mariale. Pékin., calendrier chrétien en Chine (Pf. 117).
  """
  ls$dehergne/684/0/obs="""
      P. 25 juill. 1580, à Cochin, où il célèbre sa première messe le 26 juill. (D'Elia III, 22). V. Nan-tch'ang 1er janv. 1596 (D'Elia I, 374 et II, 4) pr. « Nanciani » ... Riccius (Lus. 2, 128). M. 11 mai 1610, Pékin (JS 113, 120-146., Planchet p. 222). Fils de Giovanni Battista Ricci, pharmacien, et de Giovanna Angiolelli, famille noble, marquis de Castelvecchio (D'Elia I, cii et II, 550). HS 43, 58 le fait mourir d'abord en 1609, puis le 11 mai 1610. Portrait: Pf. 31., D'Elia I, p. vi., ARSI Rom. 185, f° 97-98., BN: Estampes, Ne 100., en couleurs dans Bortone, P. Fernando,- Gesuiti alla corte di Pechino, 1969, pl. II p. 1., cf. Hamy. Pf. 22., Koch., NCE (F. A. Rouleau)., EC (Cel. Testore)., EB (J.S. Sebes)., CE (J. Brucker)., El (Tacchi Venturi). Bibliographie: SiRErr IV, p. 525-528., XII, p. 275-283., XIV. 1. p. 778.,
  """
  ls$dehergne/684/0/obs="""
      D'Elu III, 239-243. Biographie: en chinois: BN: Courant 9 (anonyme), 1014-1016 I, par Aleni, 1321 (par Pantoja, de Ursis)., et 6832 I, poème sur Rica. BernardE-MaÎtre], H., Le P. Matthieu Ricci et la société chinoise de son temps (1552-1610), Tientsin, 1937, 2 vol.., trad. chinoise par Wang Tch'ang-Tche, J., 1943., du même, Iles Philippines, 213-218 (sur la pensée de Ricci)., Cronin, Vincent, The Wise Man front the West, Londres, 1955., Dunne, G. H., Génération of Giants, 1962, p. 23-108., trad. franç. Chinois avec les Chinois, te P. Ricci et ses compagnons, Paris, 1964., Bortone, Fernando, P. Matteo Ricci, SJ.: Il « Saggio d'Occidente », 2' éd., 1965., trad. franç. en préparation. Le ms de Pires, Francisco, montre qu'il a failli être envoyé au Japon.Son oeuvre: Nocentini, Lod., --primo Sinologo, P.M.R., Florence, 1882.,
  """
  ls$dehergne/684/0/obs="""
      Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,. Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1., Son oeuvre: Nocentini, Lod., -- primo Sinologo, P.M.R., Florence, 1882., Tacchi-Venturi, Opère storiche del P. M. R., Macerata, 1911-1912, 2 vol.., D'Elia, P. M., Fonti Ricciane, Rome, 1942-1949, 3 vol.., du même,- Grandi Missionari, t. I (Rome, 1939), 127-176., du même, Il domma cattolico integralmente présentai da M. R ai letterati delta Cina, Civ. Catt., 1935, II, 35-53., cf Gregorianum 21 (1940), 482-526., du même, Galiteo in Cina, Anatecta Gregor. il, Sect. A n° 1.,
  """
  ls$dehergne/684/0/obs="""
      id.. L'apport scientifique du P. M. R à la Chine, Tientsin, 1935, dont trad. anglaise par Chalmers Werner, Edw., Pékin, 1935., id., L'attitude du P. M. R. en face des coutumes et rites chinois, RSRel. 28 (1938), 31-47., id., Les étapes de la cartographie scientifique pour ta Chine et tes pays voisins, MS I (1936), 428-477., Brou, A., Les tâtonnements du P. M. R., RHM 15 (1938), 228-244., Szczesniak, B., The Seventeenth Maps of China, Imago Mundi 17 (1956), 116-136, 9 cartes., id., Matteo Ricci's Maps of China, ibid , 11 (1954), 127-134., cf Giles, L., Geographicat Journal 52 (1918), 367-385 et 53 (1919), 19-30., Wallis, Helen, The Influence of Father R. on Far Eastern Cartography, Imago Mundi 19 (1965), 38-45, 5 cartes., Harris, George L., The Mission of M. R. A case study of an effort at guided culture change in the Sixteenth Century, MS 25 (1968), 1-168.,
  """
  ls$dehergne/684/0/obs="""
      Bettray, Johannes, S.V.D., Die akkomodationmethode des P. M. R., S.J., in China, Analecta Gregoriana, nº 76, Rome, 411 p.., Rule, Paul A., Jestât and Confucian? Chinese Religion in the journal of M.R, Journal of Religious History (Sidney, 1969), 105-124., D'Elia, P. M., Récent discoveries and New Studies (1938-1960) on the World Map in Chinese of F. M.R., SJ., MS XX (1961), 82-164., Danibl-Rops, Histoire de t'Eglise du Christ VI (Paris, 1966), 272-276, Le Christ entre au « Cathay » avec « Li Mateou »., Schutte, 996., DI. XII, 1031. Et nombre d'études sur des points spéciaux., par exemple, sur la Congré- gation mariale de Pékin: Du Manoir, Hubert, Maria t. IV, 968-972., NZM 1962, 255 citant Margiotti...
  """
  ls$dehergne/684/0/obs="""
      Sur l'art chinois: Sepp Schûller, P. M. Ricci und die christliche Kunst, Die Kath. Miss. LXIV (Diisseldorf, 1936), 3-8., H. Bernard [Maître], L'Art chré- tien en Chine au temps du P. M. R., RHM 12 (1935), 199-229., D'Elia, Le origini delt'arte cristiana cinese, Rome 1939. Sur l'influence au Japon des cartes de Ricci, Aleni et Verbiest, l'art, de Shintarô Ayusawa, MNipp. 19 (1964), 45-49. Sur le Ki-jen che p'ien, RBS 228 et 399. Principaux autographes de RICCI: — Son catéchisme, B. Casanatense ms 2136 G. I 1, daté de 1603, cf. JS 195.
  """
  ls$dehergne/684/0/obs="""
      — Délia Entrata delta Comp. nella Cina, avec additions de N. Trigault, JS 106a. Cf D'Elia. Une édition nouvelle, avec un important appareil documentaire et critique est en préparation à l'Université de Paris VII (Bulletin de Liaison, Ecole Pratique des Hautes Etudes, VI* section, 54 bd Raspail, 75006 Paris, vol. V (1972) p. 42. — La Carte de Chine, 28 sept. 1584, reproduite dans Colin, Francisco & Pastells, Pablo, Labor Evangelica .... Barcelone, 1902, III, planche, p. 448 (Arch. d. Ind., 145-7-7). Sa carte du Monde, supra. Gaibandi, Pietro, -- P. M.R e ta geografia délia Cina, Rivista di fisica, matematica e scienze naturali, Padua, VIII, 1903, 321-355, 459-464.
  """
  ls$dehergne/684/0/obs="""
      pécimen d'écriture, nom chinois et romanisation, Allan, pl. p. 49 (noter le -RI de Ricci, écrit à la fois RI et LI. Copie de la lettre du P. « Matheo Risi y Saliano » (1584) à Juan Bautista RomAn, facteur des îles Philippines à Macao, dans Carlos Sanz, Primitivas Relaciones de Espana con Asia y Oceania, Madrid, 1958, 372-384 (Archivos de Indias 67-6-29) et l'art, de Léon Lopetegui, Miss. Hisp. I, 1944, 341-352., Razén y Fe IV, 1902, 463477.
  """
  pai$Giovanni Battista Ricci/m/id=deh-matteo-ricci-pai
    rel$function-in-act/pai/dehergne-notices-r/0
    ls$profissao/Boticário/0
    ls$ec/c/15880000
  mae$Giovanna Angiolelli/f/id=deh-matteo-ricci-mae/obs=Dehergne menciona família nobre, marqueses de Castelvecchio, mas não diz de que lado
    rel$function-in-act/mae/dehergne-notices-r/0
    ls$ec/c/15880000

#### Atributos de uma pessoa numa tabela, attributos em colunas

---

#### Person attributes in a dataframe, attributes in columns

In [55]:
# Get list of people with with a certain value in a specific attribute

id = 'deh-matteo-ricci'  # matheo ricci
# id = 'deh-antonio-de-magalhaes-ref1'  # Alexandre Metelo de Sousa
df = entities_with_attribute(
                    entity_type='person',
                    the_type='estadia',  # we need a base attribute
                    the_value='Pequim',
                    more_info=['name'],
                    more_cols=['jesuita-entrada','jesuita-estatuto','morte'],
                    dates_in=('1580','1610'),
                    db=tlnb.db,
                    sql_echo=False)
view_cols = ['name','estadia','estadia.date','morte.date','jesuita-entrada','jesuita-entrada.date']
df.info()
df[view_cols].sort_values('estadia.date')

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, deh-antonio-leitao to deh-sebastien-fernandes-tchong-ref2
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   name                   13 non-null     object
 1   estadia                13 non-null     object
 2   estadia.date           13 non-null     object
 3   estadia.obs            0 non-null      object
 4   jesuita-entrada        11 non-null     object
 5   jesuita-entrada.date   11 non-null     object
 6   jesuita-entrada.obs    0 non-null      object
 7   jesuita-estatuto       11 non-null     object
 8   jesuita-estatuto.date  11 non-null     object
 9   jesuita-estatuto.obs   0 non-null      object
 10  morte                  10 non-null     object
 11  morte.date             10 non-null     object
 12  morte.obs              0 non-null      object
dtypes: object(13)
memory usage: 1.4+ KB

,name,estadia,estadia.date,morte.date,jesuita-entrada,jesuita-entrada.date
id,,,,,,
deh-lazzaro-cattaneo,Lazzaro Cattaneo,Pequim,15980907,16400119,Roma (Noviciado de Sant'Andrea al Quirinale),15810227
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,15980907,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-sebastien-fernandes-tchong-ref2,Matteo Ricci,Pequim,15980907,NaN,NaN,NaN
deh-lazzaro-cattaneo,Lazzaro Cattaneo,Pequim,15981105,16400119,Roma (Noviciado de Sant'Andrea al Quirinale),15810227
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,15981105,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-sebastien-fernandes-tchong-ref2,Matteo Ricci,Pequim,15981105,NaN,NaN,NaN
deh-jacques-niva-ni,Jacques Niva Ni,Pequim,16020700,16381026,Nan-tch'ang,16080000
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,16020920,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-antonio-leitao,António Leitão,Pequim,16030000,16111010,?,16030000
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,16040000,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-jean-fernandes-tchong,Jean Fernandes Tchong,Pequim,16071029,NaN,Nanquim,16080300
deh-sebastien-fernandes-tchong,Sébastien Fernandes Tchong,Pequim,16080000,16211124,"Shiuchow, Chao-tcheou fou",15891100
deh-matteo-ricci,Matteo Ricci,Pequim,16090000,16100511,Roma (Noviciado de Sant'Andrea al Quirinale),15710816

#### Examinar potenciais duplicados

---

#### Examine potentital duplicates

In [71]:
from timelink.pandas.group_attributes import display_group_attributes
pd.set_option('display.max_rows',250)

no_show=['dehergne']

dup_ids = ricci.index.unique()  #

display_group_attributes(dup_ids,
                             header_cols=['estadia'],
                             exclude_attributes=no_show,
                             sort_attributes=['date','type','value'],
                             cmap_name='Pastel1')

ImportError: cannot import name 'display_group_attributes' from 'timelink.pandas' (/Users/jrc/mhk-home/sources/dehergne-locations/.venv/lib/python3.10/site-packages/timelink/pandas/__init__.py)